import { Talents } from "@/lib/types";
import { melusine } from "./melusine";

export const melusine_talents: Talents[] = [
  {
    name: "Stone Skin",
    description:
      "Quest (x40): Each successful DEFENSE grants +0.5 ARMOR. Complete: Each block triggers an attack dealing 100% of the blocked damage as area damage",
    unlock_rank: 0,
    hero: melusine.name,
    type: "starter",
    upgrade_changes: "+25% of the blocked damage",
  },
  {
    name: "Thirst For Immortality",
    description:
      "Quest (x7): Obtaining a Magical Object with Rare quality or higher grants +2 DMG. Complete: Grants +100 VITALITY but now only Hero or Magical Object heals are effective",
    unlock_rank: 0,
    hero: melusine.name,
    type: "starter",
    upgrade_changes: "+25 VITALITY",
  },
  {
    name: "Supreme Polarity",
    description:
      "Switching STANCE increases the power of the new STANCE for 7 second(s). YIN: +4% LIFE ON HIT. YANG: deals 20% more damage",
    unlock_rank: 2,
    hero: melusine.name,
    type: "starter",
    upgrade_changes: "+1% LIFE ON HIT and +5% damage",
  },
  {
    name: "Way of Awakening",
    description:
      "After 10 successful DEFENSE actions, the next TRAIT activates AWAKENED STANCE for 12 second(s). AWAKENED STANCE grants both YIN and YANG effects without taking any additional damage",
    unlock_rank: 5,
    hero: melusine.name,
    type: "starter",
    upgrade_changes: "Duration +3 second(s)",
  },
  {
    name: "Mantra of Balance",
    description:
      "When SPECIAL is triggered, it applies a negative status effect to nearby enemies within range: YIN: VULNERABLE for 4 second(s) YANG: WEAKENED for 6 second(s)",
    unlock_rank: 0,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "+1 second of VULNERABLE. +2 second(s) of WEAKENED",
  },
  {
    name: "Celestial Pillar",
    description: "",
    unlock_rank: 0,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Stick Twirl",
    description: "",
    unlock_rank: 0,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Sprint",
    description: "",
    unlock_rank: 0,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Resonance",
    description: "",
    unlock_rank: 0,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Airbender",
    description: "",
    unlock_rank: 0,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Om",
    description: "",
    unlock_rank: 0,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Om",
    description: "",
    unlock_rank: 0,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Thundercloud",
    description: "",
    unlock_rank: 2,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Mind Fortress",
    description: "",
    unlock_rank: 3,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "One-Inch Punch",
    description: "",
    unlock_rank: 3,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Fiery Dragon",
    description: "",
    unlock_rank: 4,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Frost Tiger",
    description: "",
    unlock_rank: 4,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Divine Palm",
    description: "",
    unlock_rank: 5,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Focused Strikes",
    description: "",
    unlock_rank: 7,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Saced Seal",
    description: "",
    unlock_rank: 7,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Ch'i Outburst",
    description: "",
    unlock_rank: 8,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Fiery Golden Eyes",
    description: "",
    unlock_rank: 8,
    hero: melusine.name,
    type: "normal",
    upgrade_changes: "",
  },
  {
    name: "Army of Monkeys",
    description: "",
    unlock_rank: 0,
    hero: melusine.name,
    type: "ultimate",
    upgrade_changes: "",
  },
  {
    name: "Mantra of Replication",
    description: "",
    unlock_rank: 9,
    hero: melusine.name,
    type: "ultimate",
    upgrade_changes: "",
  },
  {
    name: "Perfect Copy",
    description: "",
    unlock_rank: 6,
    hero: melusine.name,
    type: "ultimate",
    upgrade_changes: "",
  },
  {
    name: "Divine Beverage",
    description: "",
    unlock_rank: 9,
    hero: melusine.name,
    type: "ultimate",
    upgrade_changes: "",
  },
];
