import { Magical_Objects } from "../types";

export const magical_objects: Magical_Objects[] = [
  {
    id: "leprechaun-coin",
    name: "Leprechaun Coin",
    description:
      "+1 Star(s) of Fate and for each reroll performed, gain +15 Dream Shards",
    rarity: "common",
    super_effect: "Rerolling a choice is free the first time",
    stacks_to_effect: 5,
    encoding_id: "aaa",
  },
  {
    id: "dreamcatcher",
    name: "Dreamcatcher",
    description: "Reduce Sandman's Dream Shards prices by 10%",
    rarity: "common",
    super_effect: "One free purchase at the Sandman per chapter",
    stacks_to_effect: 5,
    encoding_id: "aab",
  },
  {
    id: "goldilocks-porridge",
    name: "Goldilock's Porridge",
    description: "Healing Orbs grant STRENGTH for 4 seconds (duration stacks)",
    rarity: "common",
    super_effect: "+20 DMG while STRENGTH status is active",
    stacks_to_effect: 5,
    encoding_id: "aac",
  },
  {
    id: "voodoo-doll",
    name: "Voodoo Doll",
    description: "Deal +15% damage to Bosses",
    rarity: "common",
    super_effect: "Any damage kills Bosses once they have less than 5% Health",
    stacks_to_effect: 5,
    encoding_id: "aad",
  },
  {
    id: "mermaid-tears",
    name: "Mermaid Tears",
    description: "+25% to any healing effect provided or received",
    rarity: "common",
    super_effect: "+30 VITALITY",
    stacks_to_effect: 5,
    encoding_id: "aae",
  },
  {
    id: "eternal-rose",
    name: "Eternal Rose",
    description: "After DASH, gain +10% Crit Chance for 2 seconds",
    rarity: "common",
    super_effect: "Critical Hits deal +50% damage",
    stacks_to_effect: 5,
    encoding_id: "aaf",
  },
  {
    id: "ogre-blood",
    name: "Ogre Blood",
    description: "+1 DMG for each 10 VITALITY you have",
    rarity: "common",
    super_effect: "+20% Crit Chance",
    stacks_to_effect: 5,
    encoding_id: "aag",
  },
  {
    id: "green-armor",
    name: "Green Armor",
    description: "+2 ARMOR for each Common Magical Object",
    rarity: "common",
    super_effect: "Rare Magical Objects also count",
    stacks_to_effect: 5,
    encoding_id: "aah",
  },
  {
    id: "horn-of-plenty",
    name: "Horn of Plenty",
    description: "When picked up, make 2 consumables appear",
    rarity: "common",
    super_effect: "+10 DMG, +20 VITALITY, +20 ARMOR",
    stacks_to_effect: 5,
    encoding_id: "aai",
  },
  {
    id: "fairy-dust",
    name: "Fairy Dust",
    description:
      "When taking damage, gain 18 SHIELD (Max. every 30 seconds. Amount scales with the current hero level)",
    rarity: "rare",
    super_effect: "+50% to any SHIELD applied or received",
    stacks_to_effect: 4,
    encoding_id: "aaj",
  },
  {
    id: "queen-of-hearts-card",
    name: "Queen of Hearts Card",
    description:
      "When not in combat, passively heal 2% Max Health every 2 seconds",
    rarity: "rare",
    super_effect: "+30 DMG when at full Health",
    stacks_to_effect: 4,
    encoding_id: "aak",
  },
  {
    id: "unicorn-horn",
    name: "Unicorn Horn",
    description:
      "At Critical Health, gain +4 REGENERATION (Max. every 60 seconds)",
    rarity: "rare",
    super_effect: "+50 DMG when under a REGENERATION effect",
    stacks_to_effect: 4,
    encoding_id: "aal",
  },
  {
    id: "vajra",
    name: "Vajra",
    description: "DASH deals +40 damage to all enemies passed",
    rarity: "rare",
    super_effect: "DASH casts a lightning strike at starting location",
    stacks_to_effect: 4,
    encoding_id: "aam",
  },
  {
    id: "jack-of-diamonds-card",
    name: "Jack of Diamonds Card",
    description: "SPECIAL deals +20% damage",
    rarity: "rare",
    super_effect: "SPECIAL has a +40% Crit Chance",
    stacks_to_effect: 4,
    encoding_id: "aan",
  },
  {
    id: "king-of-clubs-card",
    name: "King of Clubs Card",
    description: "POWER deals +20% damage",
    rarity: "rare",
    super_effect: "POWER has a +40% Crit Chance",
    stacks_to_effect: 4,
    encoding_id: "aao",
  },
  {
    id: "ace-of-spades-card",
    name: "Ace of Spades Card",
    description: "ATTACK deals +20% damage",
    rarity: "rare",
    super_effect: "+15% ATTACK SPEED",
    stacks_to_effect: 4,
    encoding_id: "aap",
  },
  {
    id: "dragon-hide",
    name: "Dragon Hide",
    description: "+1 ARMOR for each 5% missing health",
    rarity: "rare",
    super_effect: "ARMOR grants 40% of its value as DMG",
    stacks_to_effect: 4,
    encoding_id: "aaq",
  },
  {
    id: "golden-egg",
    name: "Golden Egg",
    description:
      "Gain +1 DMG per 150 Dream Shards spent during the game (currently: +0)",
    rarity: "rare",
    super_effect: "+30% to any Dream Shard gains",
    stacks_to_effect: 4,
    encoding_id: "aar",
  },
  {
    id: "thunderstone",
    name: "Thunderstone",
    description: "SPECIAL gains +1 charge(s)",
    rarity: "epic",
    super_effect: "SPECIAL casts a Lightning Strike upon the 3 closest enemies",
    stacks_to_effect: 3,
    encoding_id: "aas",
  },
  {
    id: "raven-eye",
    name: "Raven Eye",
    description: "Reduce ULTIMATE cooldown by +20%",
    rarity: "epic",
    super_effect: "ULTIMATE clears POWER, SPECIAL and DEFENSE cooldowns",
    stacks_to_effect: 3,
    encoding_id: "aat",
  },
  {
    id: "raven-beak",
    name: "Raven Beak",
    description: "Reduce SPECIAL cooldown by +25%",
    rarity: "epic",
    super_effect: "SPECIAL has +40% damage",
    stacks_to_effect: 3,
    encoding_id: "aau",
  },
  {
    id: "raven-claw",
    name: "Raven Claw",
    description: "Reduce POWER cooldown by +25%",
    rarity: "epic",
    super_effect: "POWER has +40% damage",
    stacks_to_effect: 3,
    encoding_id: "aav",
  },
  {
    id: "raven-skull",
    name: "Raven Skull",
    description: "Reduce DEFENSE cooldown by +25%",
    rarity: "epic",
    super_effect: "+40 ARMOR",
    stacks_to_effect: 3,
    encoding_id: "aaw",
  },
  {
    id: "raven-wing",
    name: "Raven Wing",
    description: "Reduce DASH cooldown by +25%",
    rarity: "epic",
    super_effect: "+15% Move Speed",
    stacks_to_effect: 3,
    encoding_id: "aax",
  },
  {
    id: "flaming-pearl",
    name: "Flaming Pearl",
    description: "POWER gains +1 charge(s)",
    rarity: "epic",
    super_effect:
      "POWER deals +15% damage to enemies for each Negative Status they have",
    stacks_to_effect: 3,
    encoding_id: "aay",
  },
  {
    id: "adder-stone",
    name: "Adder Stone",
    description: "DEFENSE gains +1 charge(s)",
    rarity: "epic",
    super_effect:
      "After a DEFENSE, gain +40% Move Speed decaying over 3 seconds",
    stacks_to_effect: 3,
    encoding_id: "aaz",
  },
  {
    id: "charmstone",
    name: "Charmstone",
    description: "DASH gains +1 charge(s)",
    rarity: "epic",
    super_effect:
      "DASH grants 10 SHIELD (Amount scales with the current hero level) for 6 seconds",
    stacks_to_effect: 3,
    encoding_id: "aba",
  },
  {
    id: "philosophers-stone",
    name: "Philosopher's Stone",
    description: "Gain +1 VITALITY each time you collect a Healing Orb",
    rarity: "legendary",
    super_effect: "",
    encoding_id: "abb",
  },
  {
    id: "nibelungen-ring",
    name: "Nibelungen Ring",
    description: "ULTIMATE gains an extra charge",
    rarity: "legendary",
    super_effect: "",
    encoding_id: "abc",
  },
  {
    id: "vorpal-blade",
    name: "Vorpal Blade",
    description:
      "Any damage you deal kills standard enemies below 20% Health or elite enemies below 10% Health",
    rarity: "legendary",
    super_effect: "",
    encoding_id: "abd",
  },
  {
    id: "water-of-life",
    name: "Water of Life",
    description: "+25 VITALITY\nFully Heal the start of each DAY or NIGHT",
    rarity: "legendary",
    super_effect: "",
    encoding_id: "abe",
  },
  {
    id: "tamatebako",
    name: "Tamatebako",
    description:
      "+2 Star(s) of Fate\nGet +1 choice when obtaining Magical Objects",
    rarity: "legendary",
    super_effect: "",
    encoding_id: "abf",
  },
  {
    id: "holy-grail",
    name: "Holy Grail",
    description:
      "When in combat, DEFENSE heals all nearby heroes for 10 health (Max. every 5 seconds. Amount scales with the current hero level)",
    rarity: "legendary",
    super_effect: "",
    encoding_id: "abg",
  },
  {
    id: "swan-cloak",
    name: "Swan Cloak",
    description:
      "DASH heals for +50% of damage taken over the last 2 second(s)",
    rarity: "legendary",
    super_effect: "",
    encoding_id: "abh",
  },
  {
    id: "ring-of-dispel",
    name: "Ring of Dispel",
    description: "DASH applies VULNERABLE for 3 seconds to enemies hit",
    rarity: "legendary",
    super_effect: "",
    encoding_id: "abi",
  },
  {
    id: "excalibur",
    name: "Excalibur",
    description: "+10 DMG for each Legendary Talent you have",
    rarity: "legendary",
    super_effect: "",
    encoding_id: "abj",
  },
  {
    id: "seven-league-boots",
    name: "Seven-League Boots",
    description:
      "Clear DASH's cooldown whenever you use POWER, SPECIAL, or DEFENSE",
    rarity: "legendary",
    super_effect: "",
    encoding_id: "abk",
  },
  {
    id: "golden-coat-of-chainmail",
    name: "Golden Coat of Chainmail",
    description:
      "Damage taken within 1 second(s) cannot exceed +50% of your maximum health",
    rarity: "legendary",
    super_effect: "",
    encoding_id: "abl",
  },
  {
    id: "raven-effigy",
    name: "Raven Effigy",
    description: "POWER and SPECIAL gain +1 charge(s)",
    rarity: "legendary",
    super_effect: "",
    encoding_id: "abm",
  },
  {
    id: "father-times-hourglass",
    name: "Father Time's Hourglass",
    description:
      "POWER, SPECIAL, DEFENSE have a 10% reduced cooldown for each 20% Health missing",
    rarity: "legendary",
    super_effect: "",
    encoding_id: "abn",
  },
  {
    id: "hungry-grass",
    name: "Hungry Grass",
    description: "Healing Orbs grant +1 DMG\nStacks are lost at Death's Door",
    rarity: "cursed",
    super_effect: "",
    encoding_id: "abo",
  },
  {
    id: "fast-walker-boots",
    name: "Fast-Walker Boots",
    description: "+20% Move Speed, -25 ARMOR",
    rarity: "cursed",
    super_effect: "",
    encoding_id: "abp",
  },
  {
    id: "cauldron-of-dyrnwch",
    name: "Cauldron of Dyrnwch",
    description: "+60 VITALITY, all healing effects are reduced by 25%",
    rarity: "cursed",
    super_effect: "",
    encoding_id: "abq",
  },
  {
    id: "mad-hat",
    name: "Mad Hat",
    description:
      "Taking damage earns 10% of their value as Dream Shards DreamShards",
    rarity: "cursed",
    super_effect: "",
    encoding_id: "abr",
  },
  {
    id: "hope-diamond",
    name: "Hope Diamond",
    description:
      "Gain extra 50% the amount of collected Dream Shards but lose all Dream Shards at Death's Door",
    rarity: "cursed",
    super_effect: "",
    encoding_id: "abs",
  },
  {
    id: "witchs-broom",
    name: "Witch's Broom",
    description:
      "DASH makes the hero INTANGIBLE but any damage taken is increased by +25%",
    rarity: "cursed",
    super_effect: "",
    encoding_id: "abt",
  },
  {
    id: "oni-mask",
    name: "Oni Mask",
    description:
      "+15 DMG for each Cursed Magical Object, -10 VITALITY for each Legendary Magical Object",
    rarity: "cursed",
    super_effect: "",
    encoding_id: "abu",
  },
  {
    id: "black-lotus",
    name: "Black Lotus",
    description:
      "ATTACK gains +5% Lifesteal but Healing Orbs don't affect you anymore",
    rarity: "cursed",
    super_effect: "",
    encoding_id: "abv",
  },
  {
    id: "nightmare-ichor",
    name: "Nightmare Ichor",
    description: "SPECIAL deals +100% damage but has a +50% increased cooldown",
    rarity: "cursed",
    super_effect: "",
    encoding_id: "abw",
  },
  {
    id: "nightmare-thorn",
    name: "Nightmare Thorn",
    description: "POWER deals +100% damage but has a +50% increased cooldown",
    rarity: "cursed",
    super_effect: "",
    encoding_id: "abx",
  },
  {
    id: "baba-yagas-mortar",
    name: "Baba Yaga's Mortar",
    description:
      "Prevents lethal damage and restores all health instead (only works once)",
    rarity: "cursed",
    super_effect: "",
    encoding_id: "aby",
  },
  {
    id: "balors-eye",
    name: "Balor's Eye",
    description:
      "When picked up, remove all current and future charges of POWER and SPECIAL to make them deal +100% damage per charge removed",
    rarity: "cursed",
    super_effect: "",
    encoding_id: "abz",
  },
  {
    id: "bloody-marys-mirror",
    name: "Bloody Mary's Mirror",
    description: "DMG and ARMOR stats are swapped",
    rarity: "cursed",
    super_effect: "",
    encoding_id: "aca",
  },
];
