import { Talents } from "@/lib/types";

export const carmilla_talents: Talents[] = [
  {
    id: "carmilla-bat-master",
    name: "Bat Master",
    description:
      "When not in combat, DEFENSE grants STEALTH and can be held without consuming BLOOD. DEFENSE deals +40% damage.",
    unlock_rank: 0,
    hero: "Carmilla",
    type: "starter",
    upgrade_changes: "+10% damage",
  },
  {
    id: "carmilla-life-essence",
    name: "Life Essence",
    description:
      "Quest (x30): Killing an enemy with SPECIAL's bite earns +1 VITALITY. Complete: Repeating this action restores 20 Health to Carmilla.",
    unlock_rank: 0,
    hero: "Carmilla",
    type: "starter",
    upgrade_changes: "+15 Health + Hero Level",
  },
  {
    id: "carmilla-blood-rage",
    name: "Blood Rage",
    description:
      "Quest (x20): Hitting an enemy with POWER held for at least 1 second earns +0.5 DMG. Complete: Repeating this action increases POWER explosion damage by +90%.",
    unlock_rank: 2,
    hero: "Carmilla",
    type: "starter",
    upgrade_changes: "+20% POWER explosion damage",
  },
  {
    id: "carmilla-life-tap",
    name: "Life Tap",
    description:
      "In Winged Form, activating TRAIT again consumes HEALTH equivalent to 20% of max health to recover up to 30 BLOOD points. This effect cannot be activated when health is below the required threshold and has a 5-second cooldown.",
    unlock_rank: 5,
    hero: "Carmilla",
    type: "starter",
    upgrade_changes: "+10 BLOOD points",
  },
  {
    id: "carmilla-razor-claws",
    name: "Razor Claws",
    description: "ATTACK deals +40% damage as BLEED.",
    unlock_rank: 0,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+10% damage as BLEED",
  },
  {
    id: "carmilla-puncture",
    name: "Puncture",
    description: "Each enemy passed through by DASH earns 8 BLOOD point(s).",
    unlock_rank: 0,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "",
  },
  {
    id: "carmilla-dispersion",
    name: "Dispersion",
    description:
      "After DEFENSE, bats disperse around Carmilla dealing 60 area damage as BLEED.",
    unlock_rank: 0,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "",
  },
  {
    id: "carmilla-sadism",
    name: "Sadism",
    description: "Critical Hits deal +40% damage on enemies affected by BLEED.",
    unlock_rank: 0,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+10% damage",
  },
  {
    id: "carmilla-boiling-blood",
    name: "Boiling Blood",
    description:
      "After consuming HEALTH for at least 1 second(s) to fuel an ability, gain +3 REGENERATION.",
    unlock_rank: 0,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+1 REGENERATION",
  },
  {
    id: "carmilla-furious-tempest",
    name: "Furious Tempest",
    description:
      "Consuming BLOOD to fuel POWER gradually increases its damage up to +40% after 3.0 seconds of holding.",
    unlock_rank: 0,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+10% damage",
  },
  {
    id: "carmilla-go-for-the-throat",
    name: "Go For The Throat",
    description:
      "Distance covered before SPECIAL's bite increases its Crit Chance, up to +40%.",
    unlock_rank: 0,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+10% Crit Chance",
  },
  {
    id: "carmilla-bloodletting",
    name: "Bloodletting",
    description: "POWER's explosion radius increases by +25%.",
    unlock_rank: 2,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+10% explosion radius",
  },
  {
    id: "carmilla-hemophilia",
    name: "Hemophilia",
    description:
      "Enemies affected by BLEED take +20% increased damage from Carmilla's attacks.",
    unlock_rank: 3,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+5% increased damage",
  },
  {
    id: "carmilla-blood-pact",
    name: "Blood Pact",
    description:
      "After consuming BLOOD for at least 1 second(s), Carmilla gains +5% DMG for 5 seconds.",
    unlock_rank: 3,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+2% DMG",
  },
  {
    id: "carmilla-thirsting-slash",
    name: "Thirsting Slash",
    description: "Each successful ATTACK restores +1 BLOOD point(s).",
    unlock_rank: 4,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+1 BLOOD point",
  },
  {
    id: "carmilla-bloodbath",
    name: "Bloodbath",
    description:
      "Killing an enemy with DEFENSE while in Winged Form restores +20 HEALTH.",
    unlock_rank: 4,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+5 HEALTH restored",
  },
  {
    id: "carmilla-sanguine-surge",
    name: "Sanguine Surge",
    description: "During Winged Form, Carmilla gains +15% MOVE SPEED.",
    unlock_rank: 5,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+5% MOVE SPEED",
  },
  {
    id: "carmilla-blood-moon",
    name: "Blood Moon",
    description: "Activating TRAIT during NIGHT increases Crit Damage by +25%.",
    unlock_rank: 7,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+5% Crit Damage",
  },
  {
    id: "carmilla-vampiric-feast",
    name: "Vampiric Feast",
    description: "Each BLEED tick restores +1 BLOOD point(s) to Carmilla.",
    unlock_rank: 7,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+1 BLOOD point",
  },
  {
    id: "carmilla-sanguine-blade",
    name: "Sanguine Blade",
    description: "Every 10th ATTACK deals +100% Crit Damage and applies BLEED.",
    unlock_rank: 8,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+10% Crit Damage",
  },
  {
    id: "carmilla-blood-reign",
    name: "Blood Reign",
    description:
      "POWER's explosion deals +50% damage to enemies below 30% health.",
    unlock_rank: 8,
    hero: "Carmilla",
    type: "normal",
    upgrade_changes: "+10% damage",
  },
  {
    id: "carmilla-nocturnal-wings",
    name: "Nocturnal Wings",
    description:
      "In Winged Form, Carmilla becomes INTANGIBLE for the first 2 seconds upon activation.",
    unlock_rank: 9,
    hero: "Carmilla",
    type: "ultimate",
    upgrade_changes: "+1 second INTANGIBILITY",
  },
  {
    id: "carmilla-crimson-dance",
    name: "Crimson Dance",
    description: "Using SPECIAL applies BLEED to all enemies within range.",
    unlock_rank: 9,
    hero: "Carmilla",
    type: "ultimate",
    upgrade_changes: "+5% BLEED damage",
  },
  {
    id: "carmilla-blood-sovereign",
    name: "Blood Sovereign",
    description:
      "During Winged Form, all damage dealt restores +10% of the damage as health to Carmilla.",
    unlock_rank: 9,
    hero: "Carmilla",
    type: "ultimate",
    upgrade_changes: "+5% life restoration",
  },
  {
    id: "carmilla-scarlet-tempest",
    name: "Scarlet Tempest",
    description: "ULTIMATE deals +20% damage to enemies affected by BLEED.",
    unlock_rank: 10,
    hero: "Carmilla",
    type: "ultimate",
    upgrade_changes: "+5% damage",
  },
];
