import { HeroBuild } from "@/lib/types";
import { HERO_IDS } from "../hero-ids";

export const wukong_builds: HeroBuild[] = [
  {
    version: "1.0",
    name: "Power Build",
    description: "Wukong Power build. The premier damage build for Wukong.",
    added_date: new Date("2025-01-26"),
    hero: HERO_IDS.SUN_WUKONG,
    core_talents: [
      "wukong-airbender",
      "wukong-focused-strikes",
      "wukong-thundercloud",
      "wukong-chi-outburst",
    ],
    secondary_talents: ["wukong-thirst-for-immortality"],
    required_magical_objects: [
      "king-of-clubs-card",
      "flaming-pearl",
      "raven-claw",
      "nightmare-thorn",
      "balors-eye",
    ],
    optional_magical_objects: ["ogre-blood", "philosophers-stone"],
    talents_description:
      "This build focuses on maximising Wukong's damage output. These abilities provide Wukong with a significant amount of damage, while balanced with a great amount of stagger, from Thundercloud. Focused Strikes and Airbender are the most vital parts of the build, as they provide the most amount of the damage, while also providing a long period of intangibility. Accumulating enough power cooldown, through Raven Claws, you can remain intangible almost the entire time. The build can be augmented with Thirst for Immortality, Ogre Blood and Philosopher's Stone to provide a very large amount of vitality, which will translate into a very large amount of damage.",
    tips: "Thundercloud stagger can provide a great way to crack gargoyles in Chapter 3. Consider saving gargoyle camps for day time, when you can use Thundercloud to crack them for dream shards.",
  },
  {
    version: "1.0",
    name: "WhatTheShuck's Hard Carry Build",
    description:
      "The build that WhatTheShuck uses to carry his team to victory when the he desperately needs the W.",
    hero: HERO_IDS.SUN_WUKONG,
    added_date: new Date("2025-01-26"),
    core_talents: [
      "wukong-stone-monkey",
      "wukong-airbender",
      "wukong-focused-strikes",
      "wukong-thundercloud",
      "wukong-divine-palm",
      "wukong-fiery-golden-eyes",
      "wukong-chi-outburst",
      "wukong-sprint",
    ],
    secondary_talents: ["wukong-perfect-copy", "wukong-divine-beverage"],
    talents_description:
      "These talents exenuate the power build, capitalising on the strengths of the power build. While the making useful additions to the build, such as: Fiery Golden Eyes for the increased dream shard gains, sprint for the added move speed and ability to run the map. Divine palm also serves the build extremely well, if your block timings are on point. Always run the Transfiguration Ultimate, with the upgrades being dependant on the situation, WhatTheShuck prefers Divine Beverage for co-op play, while Perfect Copy is more suited to solo. One slot is available for a situational talent, however, usually One-Inch Punch is the go to.",
    required_magical_objects: [
      "king-of-clubs-card",
      "flaming-pearl",
      "raven-claw",
      "nightmare-thorn",
      "balors-eye",
      "leprechaun-coin",
      "golden-egg",
      "tamatebako",
      "excalibur",
    ],
    optional_magical_objects: [],
    tips: "Blocking is a great form of damage in this build, with the damage of Stone Monkey, paired with the Yang stance Divine Palm damage. ",
  },
  {
    version: "1.0",
    name: "Special Build",
    description: "Wukong Special Build. Spin to win.",
    hero: HERO_IDS.SUN_WUKONG,
    added_date: new Date("2025-01-26"),
    core_talents: [
      "wukong-om",
      "wukong-sacred-seal",
      "wukong-resonance",
      "wukong-mantra-of-balance",
      "wukong-ringing-beads",
      "wukong-mantra-of-replication",
    ],
    secondary_talents: ["wukong-stick-twirl"],
    talents_description:
      "There is great synergy between Om and Sacred Seal. Ringing Beads can also be accentuated by Om's radius increasing effect. Mantra of Replication is a great option to augment your damage, considering you will be spamming Special anyway, however, it can be regarded as optional if another ultimate upgrade is preferred. Building a small amount of attack can also benefit this build, as Ringing Beads damage scales off of attack, rather than special. Stick Twirl also provides a great form of burst for the Ringing Beads, as the 5 hits from Stick Twirl will each proc an instance of damage on Ringing Beads.",
    required_magical_objects: [
      "jack-of-diamonds-card",
      "thunderstone",
      "raven-beak",
      "nightmare-ichor",
      "balors-eye",
    ],
    optional_magical_objects: ["ace-of-spades-card"],
    tips: "Wukong can only cast one Special at a time, therefore, it is important not to over index into Special cooldown, as it will not provide any additional benefit. Instead, consider focusing on building a small amount of attack or more spcecial damage / charges for Balor's Eye",
  },
  {
    version: "1.0",
    name: "Stance Build",
    description: "Become Awakened with the Wukong Stance build.",
    hero: HERO_IDS.SUN_WUKONG,
    added_date: new Date("2025-01-26"),
    core_talents: [
      "wukong-way-of-awakening",
      "wukong-mantra-of-balance",
      "wukong-resonance",
      "wukong-mind-fortress",
      "wukong-divine-palm",
      "wukong-fiery-dragon",
      "wukong-frost-tiger",
    ],
    secondary_talents: [
      "wukong-one-inch-punch",
      "wukong-stick-twirl",
      "wukong-om",
      "wukong-sacred-seal",
    ],
    talents_description:
      "This build really hinges on Way of Awakening. Wukong can be fairly strong without it, but once entering Awakened stance, you really begin to ascend. When triggering the stance, Frost Tiger and Fiery Dragon provide a great amount of upfront burst, which can be retriggered at the end of Wukong's Special, thanks to Resonance. Combined with the Weakened and Vulnerable state applied to enemies when Special is triggered, means that special charges or cooldown are vital to succeeding with this build. The build can be taken in two main directions after the core talents. The combination of Om and Sacred Seal provide a more special focused build, while the combination of One-Inch Punch and Stick Twirl can provide a more attack focused build.",
    required_magical_objects: ["thunderstone", "raven-beak", "adder-stone"],
    optional_magical_objects: ["ace-of-spades-card", "jack-of-diamonds-card"],
    tips: "Blocking to succesfuly trigger Awakened stance is key to this build, ensure that you are consistently blocking attacks to trigger the stance. Blocks can be spammed on dagger cultists and other multi-hit enemies to quickly build up the required stacks to trigger the stance.",
  },
];
